### ISSUE TITLE
Track lost bug

### ISSUE THREAD

**Issue by kznr02** [MikuroXina/bms-rs#28]
when I parse junk - elegante 02_hyper.bme, the parser will lose some track, it tells me duplicate bga change object detected, this is the original bms
```
#00101:0102030400050607
#00104:01
#00106:05
#00111:000000000000000M
#00112:0G
#00113:000000000000000N
#00114:000H000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000O000000000000
#00115:000I000L
#00116:3D
#00118:00000000000K0000
#00119:0000000J00000000

......

#00301:0102030400050607
#00311:000000000000000M
#00312:0G
#00313:00000I000000000N
#00314:000H000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000O000000000000
#00315:0000000J00000J00
#00319:00000000000S0000
```
![image](https://github.com/MikuroXina/bms-rs/assets/77726985/db110369-8e19-4c7d-b3d0-ba53b7436300)
In picture, it lose track 1 and track 3
I think there is no mistake in the beatmap, it can be played in beatoraja, maybe a bug?

**Comment by kznr02** [comment]
[02_hyper.bme.txt](https://github.com/MikuroXina/bms-rs/files/12788571/02_hyper.bme.txt)
original bms file is here, remove the .txt to use

**Comment by MikuroXina** [comment]
Yes, this is a bug. Thank you for report. I will fix it as soon as possible.
